name: flash_chat
description: A team based Chat Application.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0
  firebase_auth: ^0.11.1+6
  cloud_firestore: ^0.12.5
  firebase_messaging: ^5.0.2
  flutter_spinkit: ^4.1.2+1
  provider: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
   - family: IndieFlower
     fonts:
       - asset: fonts/IndieFlower-Regular.ttf
   - family: Lobster
     fonts:
       - asset: fonts/Lobster-Regular.ttf
   - family: Righteous
     fonts:
       - asset: fonts/Righteous-Regular.ttf